### ISSUE TITLE
Going to invalid message ID doesn't error

### ISSUE THREAD

**Issue by halkeye** [halkeye/zabox#2]
http://localhost:3000/#/messages/garbage should produce some sort of error message, but instead just gives you a page missing fields

**Comment by severest** [comment]
Fixed by commit  4caee79c305a2d6f4417340473f967d61f99263f

**Comment by halkeye** [comment]
awesome

ps, if you do a commit message that includes "fixes #2" it'll auto close the issue and link any appropriate commits.

**Comment by severest** [comment]
i was wondering how to do that..
