### ISSUE TITLE
Switch Plain/HTML selector to tabs

### ISSUE THREAD

**Issue by halkeye** [halkeye/zabox#4]
I tried out the bootstrap 3 tabs support, but I Couldn't figure out how to make one of the two tabs disabled if a body type isn't provided.
Plus formatting

I kinda like the look of them in the documentation as it really highlights which one is selected.

**Comment by severest** [comment]
Had a similar issue, I just hid the tab if there is no content to display, check out branch `selectortabs`

**Comment by halkeye** [comment]
![image](https://cloud.githubusercontent.com/assets/110087/7218201/1c8f5338-e615-11e4-8872-59baf52cfe31.png)

Sweet you can paste screenshots.

I don't know if its my monitor. The tabs are not really readable.

I did notice you can add the disabled class to the li, which would give you a proper cursor, but it doesn't prevent clicking on things.

**Comment by severest** [comment]
i agree, not very readable, i'll try some different stylings

**Comment by severest** [comment]
![image](https://cloud.githubusercontent.com/assets/2700401/7220519/050fae46-e67f-11e4-8619-0aa341898c52.png)

Increased text size and changed active color to white

**Comment by halkeye** [comment]
Nice, looks slick

**Comment by severest** [comment]
![image](https://cloud.githubusercontent.com/assets/2700401/7220569/565e8932-e681-11e4-8fdc-8ba388adbb12.png)

tried merging the message content into the tab
