### ISSUE TITLE
'gulp travis' hangs

### ISSUE THREAD

**Issue by severest** [halkeye/zabox#9]
Travis CI build appears to be failing, tests are succeeding but process hangs when they are complete on my machine

**Comment by halkeye** [comment]
https://travis-ci.org/halkeye/zabox/jobs/60053101

0.10 doesn't work with smtp test

Are you running linux or windows?

**Comment by halkeye** [comment]
oh my linux vm hangs too, hrm, a callback isn't called

**Comment by severest** [comment]
macos

**Comment by halkeye** [comment]
Totally forgot to tag the commit b2512be should fix it

**Comment by severest** [comment]
7 minutes, that's gotta be a record
